"""Initial migration

Revision ID: e283d11561ee
Revises: 
Create Date: 2026-02-08 18:26:57.451470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e283d11561ee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SKIPPING DROPS OF DJANGO TABLES
    
    op.alter_column('chat_sessions', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('chat_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('chat_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    
    # Handling ChatSession indices and FK
    # We attempt to drop existing index/FK if they exist with specific names, 
    # but we might just create the new ones if needed.
    # Safe to proceed with these as they align schema.
    op.drop_index(op.f('chat_sessions_user_id_6ab420a0'), table_name='chat_sessions')
    op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=False)
    op.drop_constraint(op.f('chat_sessions_user_id_6ab420a0_fk_users_id'), 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'chat_sessions', 'users', ['user_id'], ['id'])
    
    op.alter_column('document_templates', 'template_content',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('document_templates', 'fields',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=True)
    op.alter_column('document_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('document_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index(op.f('ix_document_templates_id'), 'document_templates', ['id'], unique=False)
    
    op.alter_column('documents', 'content',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('documents', 'embedding_vector',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('messages', 'sources',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=True)
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_index(op.f('messages_session_id_8b58efc4'), table_name='messages')
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.drop_constraint(op.f('messages_session_id_8b58efc4_fk_chat_sessions_id'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'chat_sessions', ['session_id'], ['id'])
    
    # Users table modifications - Minimal touches
    # We DO NOT drop password or other columns.
    # We keep existing unique constraints (removed drop_constraint)
    # We keep existing indices (removed drop_index for patterns) unless necessary
    
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)

    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    
    # REMOVED DROPS of is_staff, date_joined, etc.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Reversing changes
    
    op.drop_index(op.f('ix_users_id'), table_name='users')
    
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)

    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_session_id_8b58efc4_fk_chat_sessions_id'), 'messages', 'chat_sessions', ['session_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.create_index(op.f('messages_session_id_8b58efc4'), 'messages', ['session_id'], unique=False)
    op.alter_column('messages', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('messages', 'sources',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('messages', 'content',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.alter_column('documents', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('documents', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('documents', 'embedding_vector',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('documents', 'content',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_document_templates_id'), table_name='document_templates')
    op.alter_column('document_templates', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('document_templates', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('document_templates', 'fields',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('document_templates', 'template_content',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('chat_sessions_user_id_6ab420a0_fk_users_id'), 'chat_sessions', 'users', ['user_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.drop_index(op.f('ix_chat_sessions_id'), table_name='chat_sessions')
    op.create_index(op.f('chat_sessions_user_id_6ab420a0'), 'chat_sessions', ['user_id'], unique=False)
    op.alter_column('chat_sessions', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('chat_sessions', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('chat_sessions', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    
    # ### end Alembic commands ###
